### ISSUE TITLE
Churrasco de comemoração da vitória

### ISSUE THREAD

**Issue by rafaelcaue** [lsa-pucrs/mas-pc-pucrs-2016#86]
:tada: :tada: :tada: 

A ideia é fazer semana que vem já (se uma boa quantidade de pessoas responder a tempo).

Marquem as datas que vocês podem ir (podem marcar mais de uma) nesse google form: https://docs.google.com/forms/d/e/1FAIpQLSfm6u_1Z998Jp5yZEidJ6gVYfc_Co-R5SLnaQFCNmYgwsjjpw/viewform

O Artur ofereceu ser na casa dele.
A princípio vai ser la a menos que alguém tenha outra sugestão.

Abraço.

ps. sim, vamos comprar o livro da imagem!

**Comment by WaGjUb** [comment]
=D

**Comment by rafaelcaue** [comment]
Pessoal, 4 pessoas responderam sem nome.
Eu apaguei essas respostas, favor colocar o nome quando escolher as datas.

[]s

**Comment by meneguzzi** [comment]
## Uma delas foi minha, mas daí eu percebi a babaquice e fiz de novo.

Dr. Felipe Meneguzzi
PUCRS | FACIN
Av Ipiranga 6681 - P32 - S622
Porto Alegre, RS - Brasil
tel: +55 51 3353 8622
felipe.meneguzzi@pucrs.brmailto:felipe.meneguzzi@pucrs.br
http://lattes.cnpq.br/5973550650941724

On 15 Sep 2016, at 17:25, Rafael Cauê Cardoso <notifications@github.com<mailto:notifications@github.com>> wrote:

Eu apaguei essas respostas, favor colocar o nome quando escolher as datas.

**Comment by rafaelcaue** [comment]
Esse poll foi quase mais emocionante que o contest!!

Como empatou entre quinta e sexta, e nenhuma das partes poderia trocar os dias, resolvemos deixar para semana que vem.

Dessa vez só entre quinta e sexta (é multipla opção, pode marcar os 2 se quiser). 
Coloquei o campo nome obrigatório agora (não tinha visto essa opção antes).

https://goo.gl/forms/vUdrKrXaDfoCQINA3

Se alguém não puder em ambos, mas pode terça ou quarta ou sabado, marca o campo other e informa a data.

**Comment by rafaelcaue** [comment]
O churrasco vai ser nessa quinta-feira 29/09!

Valor e hora a combinar na reunião do artigo de hoje.

Depois que tiver os detalhes envio por e-mail para todos que confirmaram.

:beers:

**Comment by rafaelcaue** [comment]
Lembrando que o churras vai ser hoje na casa do Artur.
Mandei um convite para quem confirmou com o endereço.

Adicionei uma foto a notícia que tinha postado no site do SMART.
https://smart-pucrs.github.io/news/2016/first-place-mapc-2016

**Comment by meneguzzi** [comment]
Tu criaste uma issue para falar de churrasco?!? Só para sacanear o algoritmo de aprendizado do Github.
Se o churrasco ficar ruim tu vais deixar a issue em aberto?

**Comment by rafaelcaue** [comment]
hahaha

Ninguém olhava quando eu criava na wiki.
Com a issue todo mundo (que quer) recebe e-mail, e não tenho que ficar adicionando se fosse escrever e-mail (ou fazer uma lista).

Mas gostei da ideia de deixar em aberto se ficar ruim!

**Comment by rafaelcaue** [comment]
Acho que todos que foram concordariam que o churrasco que o Artur fez ficou ótimo!

Logo estou fechando a issue, resolvido com sucesso.
